---
- name: Clone opencv_cam
  ansible.builtin.git:
    repo: https://github.com/clydemcqueen/opencv_cam.git
    dest: /home/{{ ansible_env.USER }}/opencv_cam_ws/src/opencv_cam
    update: false

- name: Clone ros2_shared
  ansible.builtin.git:
    repo: https://github.com/ptrmu/ros2_shared.git
    dest: /home/{{ ansible_env.USER }}/opencv_cam_ws/src/ros2_shared
    update: false


- name: Run colcon build for ~/opencv_cam_ws
  # explicitly source the ros environment
  ansible.builtin.shell: source /opt/ros/$ROS_DISTRO/setup.bash && colcon build
  args:
    chdir: /home/{{ ansible_env.USER }}/opencv_cam_ws
    executable: /bin/bash

- name: Source ROS setup for {{ ansible_env.USER }}
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc
    line: source /home/{{ ansible_env.USER }}/opencv_cam_ws/install/local_setup.bash
    state: present

- name: Source ROS setup for noninteractive bash for {{ ansible_env.USER }}
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc_noninteractive
    line: source /home/{{ ansible_env.USER }}/opencv_cam_ws/install/local_setup.bash
    state: present