---
- name: Clone opencv_cam
  ansible.builtin.git:
    repo: https://github.com/clydemcqueen/opencv_cam.git
    dest: /home/{{ ansible_env.USER }}/opencv_cam_ws/src/opencv_cam
    update: false

- name: Clone ros2_shared
  ansible.builtin.git:
    repo: https://github.com/ptrmu/ros2_shared.git
    dest: /home/{{ ansible_env.USER }}/opencv_cam_ws/src/ros2_shared
    version: 02433ef4f873876c3dd3ab2925987cf04d224660

- name: Run rosdep install, runs every time
  ansible.builtin.command:
  args:
    cmd: rosdep install --from-paths src --ignore-src --rosdistro foxy -r -y
    chdir: /home/{{ ansible_env.USER }}/opencv_cam_ws

- name: Run colcon build for ~/opencv_cam_ws
  # explicitly source the ros environment
  ansible.builtin.shell: source /home/{{ ansible_env.USER }}/.bashrc_noninteractive && colcon build
  args:
    chdir: /home/{{ ansible_env.USER }}/opencv_cam_ws
    executable: /bin/bash

- name: Source ROS setup for {{ ansible_env.USER }}
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc
    line: source /home/{{ ansible_env.USER }}/opencv_cam_ws/install/local_setup.bash
    state: present

- name: Source ROS setup for noninteractive bash for {{ ansible_env.USER }}
  ansible.builtin.lineinfile:
    path: /home/{{ ansible_env.USER }}/.bashrc_noninteractive
    line: source /home/{{ ansible_env.USER }}/opencv_cam_ws/install/local_setup.bash
    state: present